# Flyway configuration file
flyway.url=jdbc:postgresql://db:5432/orchestrator
flyway.user=postgres
flyway.password=postgres
flyway.locations=filesystem:/flyway/sql
flyway.baselineOnMigrate=true
flyway.schemas=orchestrator
flyway.cleanDisabled=false