// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/aggregator.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReportResult - Node reports task completion
type ReportResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`             // UUID of the task
	AttemptId     int64                  `protobuf:"varint,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`   // Attempt ID from task_attempt table
	LeaseToken    string                 `protobuf:"bytes,3,opt,name=lease_token,json=leaseToken,proto3" json:"lease_token,omitempty"` // Security token proving lease ownership
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`                           // "succeeded" or "failed"
	ResultRef     string                 `protobuf:"bytes,5,opt,name=result_ref,json=resultRef,proto3" json:"result_ref,omitempty"`    // S3 URI: "s3://results/output.txt"
	Metrics       string                 `protobuf:"bytes,6,opt,name=metrics,proto3" json:"metrics,omitempty"`                         // JSON string: {"duration_ms": 8234, "tokens": 156}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_proto_aggregator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aggregator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_aggregator_proto_rawDescGZIP(), []int{0}
}

func (x *ReportResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportResultRequest) GetAttemptId() int64 {
	if x != nil {
		return x.AttemptId
	}
	return 0
}

func (x *ReportResultRequest) GetLeaseToken() string {
	if x != nil {
		return x.LeaseToken
	}
	return ""
}

func (x *ReportResultRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportResultRequest) GetResultRef() string {
	if x != nil {
		return x.ResultRef
	}
	return ""
}

func (x *ReportResultRequest) GetMetrics() string {
	if x != nil {
		return x.Metrics
	}
	return ""
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"` // Always true if accepted
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`            // Optional info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_proto_aggregator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aggregator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_aggregator_proto_rawDescGZIP(), []int{1}
}

func (x *ReportResultResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ReportResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_aggregator_proto protoreflect.FileDescriptor

const file_proto_aggregator_proto_rawDesc = "" +
	"\n" +
	"\x16proto/aggregator.proto\x12\n" +
	"aggregator\"\xbf\x01\n" +
	"\x13ReportResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\x03R\tattemptId\x12\x1f\n" +
	"\vlease_token\x18\x03 \x01(\tR\n" +
	"leaseToken\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"result_ref\x18\x05 \x01(\tR\tresultRef\x12\x18\n" +
	"\ametrics\x18\x06 \x01(\tR\ametrics\"T\n" +
	"\x14ReportResultResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2_\n" +
	"\n" +
	"Aggregator\x12Q\n" +
	"\fReportResult\x12\x1f.aggregator.ReportResultRequest\x1a .aggregator.ReportResultResponseB\x15Z\x13proto/aggregator/v1b\x06proto3"

var (
	file_proto_aggregator_proto_rawDescOnce sync.Once
	file_proto_aggregator_proto_rawDescData []byte
)

func file_proto_aggregator_proto_rawDescGZIP() []byte {
	file_proto_aggregator_proto_rawDescOnce.Do(func() {
		file_proto_aggregator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_aggregator_proto_rawDesc), len(file_proto_aggregator_proto_rawDesc)))
	})
	return file_proto_aggregator_proto_rawDescData
}

var file_proto_aggregator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_aggregator_proto_goTypes = []any{
	(*ReportResultRequest)(nil),  // 0: aggregator.ReportResultRequest
	(*ReportResultResponse)(nil), // 1: aggregator.ReportResultResponse
}
var file_proto_aggregator_proto_depIdxs = []int32{
	0, // 0: aggregator.Aggregator.ReportResult:input_type -> aggregator.ReportResultRequest
	1, // 1: aggregator.Aggregator.ReportResult:output_type -> aggregator.ReportResultResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_aggregator_proto_init() }
func file_proto_aggregator_proto_init() {
	if File_proto_aggregator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_aggregator_proto_rawDesc), len(file_proto_aggregator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_aggregator_proto_goTypes,
		DependencyIndexes: file_proto_aggregator_proto_depIdxs,
		MessageInfos:      file_proto_aggregator_proto_msgTypes,
	}.Build()
	File_proto_aggregator_proto = out.File
	file_proto_aggregator_proto_goTypes = nil
	file_proto_aggregator_proto_depIdxs = nil
}
